### PR TITLE
Rahimi and Recht approx

### PR DESCRIPTION
**Pull request by thilk**
core/ccm.py: implement rank-D approximate kernel evaluations, arXiv:1707.01164 eq. 21

examples/: add 'regression_approx' dataset and 'approximate nonlinear regression' test case for rank-D approximate kernel evaluations

Tested and works well for large datasets.

### CODE REVIEW

**Comment by Jianbo-Lab** [comment]
Thank you for implementing this:)

**Comment by thilk** [comment]
I also have some code for Monte Carlo estimation of the gaussian kernel bandwidth 'sigma', if you would like to see a PR for that as well (?).

The full tensor median calculation for estimating 'sigma' in the upstream master branch can raise MemoryError on sufficiently large datasets-- even when the underlying feature selection algorithm would not do so.  It appears to be the primary memory bottleneck at present.

**Comment by Jianbo-Lab** [comment]
Just to clarify, by "Monte Carlo estimation", do you first sample a subset of x_i (the data), then use the same code to compute the median of their pairwise distance? Or directly sampling a subset of pairwise distances, and compute their median as an estimate?

**Comment by thilk** [comment]
The version I am using takes the median of a direct sample of pairwise distances, sampled from among all observations x_i in the design matrix X, if the tensor would have a size in bytes exceeding a certain large threshold.

When using a sufficiently large sample size (e.g. 65536 sample norms), simulation studies on datasets sampled from distributions with large or infinite skewness or even infinite mean (a design matrix X in which some or all columns were sampled from e.g. `np.random.lognormal(size=nobs)`, `scipy.stats.fisk.rvs(0.5, size=nobs)`, `np.exp(np.random.lognormal(size=nobs))`, `(1.0/np.random.exponential(size=nobs))`, `np.abs(SS.cauchy.rvs(0.5,size=nobs))`, etc.) showed discrepancies of only a few percent at worst.  On less extreme distributions, error was negligible.

Granted, given the typically merely heuristic justifications in the literature for using the median for first-pass automatic Gaussian kernel bandwidth selection, my view is that a close approximation of the median is likely still acceptable, compared to merely raising a MemoryError on e.g. a 1.2-trillion-element tensor.  Theoretically, the proper thing to do is probably cross-validated kernel bandwidth selection over the quality of the fits resulting from the corresponding selected feature sets, but that seems beyond the scope of this implementation.

**Comment by Jianbo-Lab** [comment]
I see. I agree with you. Given that you've added the scalable version of CCM, the median calculation indeed becomes the bottleneck. It would be great if you send another merge request for the median estimation code, or draft of it is also fine. Explaining comments like "Take the median of a subset of sampled observations x_i in the design matrix X" may be added to code if convenient. Thanks!

**Pull request merged**
